sudo: required
dist: trusty

branches:
  only: travis-ci-dev

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw -q clean verify
      before_script:
        - chmod +x src/cms-api/mvnw
        - cd ./src/cms-api/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./src/cms-client/
      script:
        - npm run build