language: minimal

jobs:
  include:
    - stage: "Tests"                
      name: "Unit Tests"           
      #script: ./unit-tests to be added later
      name: "Integration Tests" 
	  #script: ./integration-tests to be added later    
    - stage: deploy
      name: "Deployment"
      #script: ./deploy to be added later