language: minimal

jobs:
  include:
    - stage: "Tests"               
      name: "Unit Tests"            
      #script: ./unit-tests #this will be added later
    - script: #./integration-tests #this will be added later
      name: "Integration Tests"     
    - stage: deploy
      name: "Deployment"
      #script: ./deploy #this will be added later