sudo: required
dist: trusty

branches:
  only: travis-ci-dev

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw test -B -q
      before_script:
        - cd ./src/cms-api/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./src/cms-client/
      script:
        - npm run build
        - npm run e2e