sudo: required
dist: trusty

branches:
  only:
  - master
  - dev

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw -q clean verify
      before_script:
        - chmod +x src/cms-api/mvnw
        - cd ./src/cms-api/

    - language: node_js
      node_js: stable
      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      cache:
        directories:
          - ./node_modules
      install:
        - npm cache clean --force
        - npm install 
        - npm install ngx-file-drop --save
      before_install:
        - cd ./src/cms-client/
      script:
        - npm run build
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
