# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
# Frontend Service 
  client:
    build:
      context: src/cms-client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200" 
    restart: always
    depends_on:
      - server
    networks:
      - frontend 

  # Backend service
  server:
    build:
      context: src/cms-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CMS?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: soen490
      SPRING_DATASOURCE_PASSWORD: soen490     
    networks: # Networks to join
      - backend
      - frontend

  # Database Service 
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: cms-db
      MYSQL_USER: soen490
      MYSQL_PASSWORD: soen490
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/db:/var/lib/mysql
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks
networks:
  backend:
  frontend: 